### ISSUE TITLE
Code Blocks

### ISSUE THREAD

**Issue by Hashemian01** [mwxgaf/obsidian-dynamic-rtl#11]
Enabling dynamic RTL causes code blocks to ignore enters in reading view
![image](https://user-images.githubusercontent.com/48093461/198887428-969250e0-adae-42eb-90f1-545b86654e9a.png)

**Comment by mwxgaf** [comment]
Hi thanks for your new useful issues(#10 & #11). If I don't face any problems in my life; I will check them out in weekend (Iranian weekend) In-Sha-Allah. (Because I don't have much time But continue posting your issues they are very usefull I willl check them out in weekends as soon as I can) Thanks Again

**Comment by mwxgaf** [comment]
Fixed!
Thank you so so much :rose:
Wait for the new version to release.
